AWSTemplateFormatVersion: '2010-09-09'
Description: Create a security group with rules for SSH and HTTP.
# Author: Frank Ekwomadu. C

Parameters:
  VpcId:
    Type: String
    Description: VPC ID where the Security Group will be created.

Resources:
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH and HTTP access
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0 # Allow SSH from anywhere
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0 # Allow HTTP from anywhere

Outputs:
  SecurityGroupId:
    Value: !Ref MySecurityGroup
    Export:
      Name: MySecurityGroupId